### ISSUE TITLE
Question: a javascript app running Irmin and synchronising with an Irmin Git backend?

### ISSUE THREAD

**Issue by dm3** [talex5/irmin-js#1]
What would be the easiest way of achieving that? Is it possible to do without writing Ocaml at this stage?

Sorry for asking here - please direct me to a better venue for questions if this one is not appropriate.

**Comment by talex5** [comment]
You'll need to write a bit of OCaml because it doesn't currently export an API for sync. There is code for sync to a Git-format server in CueKeeper, but you also need the `git-format` branch of irmin-indexeddb, which isn't released yet.

**Comment by dm3** [comment]
Thanks, will take a look.
